# Generated by Django 4.2.6 on 2023-11-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservotemodel',
            name='user_audio_file',
        ),
        migrations.CreateModel(
            name='UserAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='user_vote_media', verbose_name='Путь к аудио')),
                ('user_voice_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_vote.uservotemodel')),
            ],
        ),
    ]
