# Generated by Django 4.2.6 on 2023-11-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_vote', '0002_remove_uservotemodel_user_audio_file_useraudiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraudiofile',
            name='test_field',
            field=models.CharField(blank=True, null=True, verbose_name='Сука заработай'),
        ),
        migrations.AlterField(
            model_name='useraudiofile',
            name='user_voice_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_vote.uservotemodel', verbose_name='Принадлежит голосу'),
        ),
    ]
