# Generated by Django 4.2.6 on 2023-11-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_vote', '0003_useraudiofile_test_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraudiofile',
            name='test_field',
        ),
    ]
