# Generated by Django 4.2.6 on 2024-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_vote', '0005_alter_useraudiofile_audio_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uservotemodel',
            name='user_vote_u_audio_n_499fe4_idx',
        ),
        migrations.AddField(
            model_name='uservotemodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddIndex(
            model_name='uservotemodel',
            index=models.Index(fields=['audio_name', 'is_deleted'], name='user_vote_u_audio_n_1f83fc_idx'),
        ),
    ]
