# Generated by Django 4.2.6 on 2023-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='audio_file',
            field=models.FileField(upload_to='', verbose_name='audio_file'),
        ),
    ]
