# Generated by Django 4.2.6 on 2023-11-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votemodel',
            name='audio_file',
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='vote_media', verbose_name='Путь к аудио')),
                ('voice_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votemodel', verbose_name='Принадлежит голосу')),
            ],
        ),
    ]
