# Generated by Django 4.2.6 on 2023-11-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_votemodel_audio_file_audiofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioFile',
            new_name='AudioFileModel',
        ),
    ]
