# Generated by Django 4.2.6 on 2023-10-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_votemodel_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemodel',
            name='audio_name',
            field=models.CharField(default='filename', max_length=20, verbose_name='Название голоса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='audio_file',
            field=models.FileField(upload_to='', verbose_name='Путь к аудио'),
        ),
    ]
