# Generated by Django 4.2.6 on 2023-10-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_votemodel_audio_name_alter_votemodel_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='audio_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название голоса'),
        ),
    ]
