# Generated by Django 4.2.6 on 2024-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_audiofilemodel_audio_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='votemodel',
            name='vote_votemo_audio_n_ae709e_idx',
        ),
        migrations.AddField(
            model_name='votemodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddIndex(
            model_name='votemodel',
            index=models.Index(fields=['audio_name', 'is_deleted'], name='vote_votemo_audio_n_e66813_idx'),
        ),
    ]
