# Generated by Django 4.2.6 on 2023-10-17 04:57

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('vote', '0004_alter_votemodel_audio_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votemodel',
            options={'ordering': ['audio_name']},
        ),
        migrations.AddField(
            model_name='votemodel',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='votemodel',
            index=models.Index(fields=['audio_name'], name='vote_votemo_audio_n_ae709e_idx'),
        ),
    ]
