# Generated by Django 4.2.6 on 2023-10-17 07:31

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('vote', '0005_alter_votemodel_options_votemodel_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='audio_file',
            field=models.FileField(unique=True, upload_to='vote_media', verbose_name='Путь к аудио'),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
    ]
