# Generated by Django 4.2.6 on 2023-10-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0003_votemodel_audio_name_alter_votemodel_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_add', models.DateTimeField(auto_created=True, editable=False, verbose_name='Время добавления')),
                ('text', models.CharField(max_length=100, verbose_name='Озвученный текст')),
                ('audio_file', models.FileField(upload_to='history/history_media', verbose_name='Результат озвучивания')),
                ('use_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votemodel')),
            ],
        ),
    ]
