# Generated by Django 4.2.6 on 2023-10-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_votemodel_audio_name'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='use_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votemodel', to_field='audio_name'),
        ),
    ]
