# Generated by Django 4.2.6 on 2023-10-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='use_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votemodel', verbose_name='Используемый голос'),
        ),
        migrations.AddIndex(
            model_name='historymodel',
            index=models.Index(fields=['text'], name='history_his_text_097e2f_idx'),
        ),
    ]
