# Generated by Django 4.2.6 on 2023-10-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_historymodel_use_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='time_add',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Время добавления'),
        ),
    ]
