# Generated by Django 4.2.6 on 2023-11-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('history', '0004_alter_historymodel_audio_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historymodel',
            name='history_his_text_097e2f_idx',
        ),
        migrations.RemoveField(
            model_name='historymodel',
            name='use_vote',
        ),
        migrations.AddField(
            model_name='historymodel',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historymodel',
            name='object_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='historymodel',
            index=models.Index(fields=['text', 'content_type', 'object_id'], name='history_his_text_3edeab_idx'),
        ),
    ]
