# Generated by Django 4.2.6 on 2023-10-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_votemodel_audio_name'),
        ('history', '0004_alter_historymodel_time_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historymodel',
            options={'ordering': ['text']},
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='use_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votemodel', verbose_name='Используемый голос'),
        ),
        migrations.AddIndex(
            model_name='historymodel',
            index=models.Index(fields=['text'], name='history_his_text_097e2f_idx'),
        ),
    ]
