# Generated by Django 4.2.6 on 2023-10-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_historymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='audio_file',
            field=models.FileField(unique=True, upload_to='history_media', verbose_name='Результат озвучивания'),
        ),
    ]
