# Generated by Django 4.2.6 on 2023-11-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('history', '0005_remove_historymodel_history_his_text_097e2f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model__in', ['uservotemodel', 'votemodel'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип голоса'),
        ),
        migrations.AlterField(
            model_name='historymodel',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Принадлежит голосу'),
        ),
    ]
