# Generated by Django 4.2.6 on 2023-11-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_alter_historymodel_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Озвученный текст'),
        ),
    ]
