# Generated by Django 4.2.6 on 2023-12-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_alter_historymodel_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historymodel',
            options={'ordering': ['-time_add', 'text']},
        ),
        migrations.RemoveIndex(
            model_name='historymodel',
            name='history_his_text_3edeab_idx',
        ),
        migrations.AddIndex(
            model_name='historymodel',
            index=models.Index(fields=['text', 'content_type', 'object_id', 'time_add'], name='history_his_text_3faa63_idx'),
        ),
    ]
