# Generated by Django 4.2.6 on 2024-02-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_alter_historymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
