# Generated by Django 4.2.6 on 2023-11-26 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAudioManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='ID задачи')),
                ('status', models.CharField(max_length=100, verbose_name='Статус задачи')),
                ('rel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель задачи')),
            ],
            options={
                'ordering': ['task_id'],
                'indexes': [models.Index(fields=['task_id'], name='text_to_aud_task_id_44a415_idx')],
            },
        ),
    ]
