# Generated by Django 4.2.6 on 2023-11-26 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_audio_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskaudiomanagermodel',
            options={'ordering': ['time_add']},
        ),
        migrations.RemoveIndex(
            model_name='taskaudiomanagermodel',
            name='text_to_aud_task_id_44a415_idx',
        ),
        migrations.AddField(
            model_name='taskaudiomanagermodel',
            name='text',
            field=models.CharField(default='1234', max_length=400, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskaudiomanagermodel',
            name='time_add',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время добавления задачи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskaudiomanagermodel',
            name='status',
            field=models.CharField(choices=[('executing', 'Выполняется'), ('complete', 'Завершен'), ('error', 'Ошибка')], max_length=100, verbose_name='Статус задачи'),
        ),
        migrations.AddIndex(
            model_name='taskaudiomanagermodel',
            index=models.Index(fields=['task_id', 'time_add'], name='text_to_aud_task_id_24e9a4_idx'),
        ),
    ]
