# Generated by Django 4.2.6 on 2023-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_audio_manager', '0002_alter_taskaudiomanagermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskaudiomanagermodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='taskaudiomanagermodel',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус задачи'),
        ),
    ]
